'use strict';
const $=id=>document.getElementById(id);
const dates=Array.from({length:36},(_,i)=>{const d=new Date(Date.UTC(2026,8,30+i));return d.toISOString().slice(0,10)});
const keys=['title','place','emotion','story','thought','reflection','behavior','lesson','person','caption'];
const profileLabels={name:'Nombre completo',school:'Escuela',subject:'Asignatura',group:'Grupo',studentId:'Boleta / matrícula',teacher:'Docente'};
let db,state={version:1,profile:{},entries:{}},selected=dates[0],picture='',dirty=false,photoBusy=false,writeQueue=Promise.resolve();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=d=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
function notice(message,bad=false){$('notice').textContent=message;$('notice').className='alert '+(bad?'alert-danger':'alert-info')}
function complete(e){return !!e&&['place','emotion','story','thought','reflection','behavior','lesson','person'].every(k=>e[k]?.trim())&&!!e.photo}
function status(e){return complete(e)?'Completo':e?'Borrador':'Pendiente'}
function persist(next){const task=writeQueue.then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('diary','readwrite');tx.objectStore('diary').put(next,'data');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Guardado cancelado'));}));writeQueue=task.catch(()=>{});return task}
async function commit(next){await persist(next);state=next}
function currentEntry(){const entry={};keys.forEach(k=>entry[k]=$(k).value.trim());entry.intensity=Number($('intensity').value);entry.photo=picture;return entry}
function profileValues(){return Object.fromEntries(Object.keys(profileLabels).map(k=>[k,$('profile-'+k).value.trim()]))}
function showPhoto(){const show=!!picture;$('photo-figure').hidden=!show;if(show)$('photo-preview').src=picture;else $('photo-preview').removeAttribute('src')}
function renderCalendar(){let html='';for(const [month,name] of [['09','Septiembre'],['10','Octubre'],['11','Noviembre']]){const list=dates.filter(d=>d.slice(5,7)===month);const offset=(new Date(list[0]+'T12:00:00').getDay()+6)%7;html+=`<div class="month-title">${name} 2026</div><div class="month-grid">`+['L','M','M','J','V','S','D'].map(d=>`<span class="weekday">${d}</span>`).join('')+'<span></span>'.repeat(offset)+list.map(d=>`<button type="button" class="day ${state.entries[d]?(complete(state.entries[d])?'complete':'draft'):''} ${d===selected?'active':''}" data-date="${d}" aria-label="${esc(label(d))}: ${status(state.entries[d])}" ${d===selected?'aria-current="date"':''}>${Number(d.slice(8))}</button>`).join('')+'</div>'} $('calendar').innerHTML=html;const n=Object.values(state.entries).filter(complete).length;$('count').textContent=`${n} / 36`;$('progress').style.width=`${n/36*100}%`;$('progress').parentElement.setAttribute('aria-valuenow',n)}
function loadDay(d){selected=d;const e=state.entries[d]||{};keys.forEach(k=>$(k).value=e[k]||'');$('intensity').value=e.intensity||3;$('intensity-value').textContent=$('intensity').value+' / 5';picture=e.photo||'';$('photo').value='';$('photo-status').textContent='';showPhoto();$('day-title').textContent=label(d);$('day-number').textContent='DÍA '+String(dates.indexOf(d)+1).padStart(2,'0');$('entry-status').textContent=status(state.entries[d]);$('save-status').textContent=e.updatedAt?'Guardado · '+new Date(e.updatedAt).toLocaleString('es-MX'):'Listo para escribir';$('previous').disabled=d===dates[0];$('next').disabled=d===dates.at(-1);dirty=false;renderCalendar()}
async function saveDay(){if(photoBusy){notice('Espera a que termine de cargar la imagen.',true);return false}try{const entry=currentEntry();const hasContent=keys.some(k=>entry[k])||entry.photo;const next=structuredClone(state);next.profile=profileValues();if(hasContent)next.entries[selected]={...entry,updatedAt:new Date().toISOString()};else delete next.entries[selected];await commit(next);dirty=false;$('entry-status').textContent=status(state.entries[selected]);$('save-status').textContent='Guardado en este navegador · '+new Date().toLocaleTimeString('es-MX');renderCalendar();return true}catch(e){notice('No se pudo guardar. No cierres esta página. Descarga un respaldo para conservar lo que has escrito. '+e.message,true);return false}}
async function switchDay(d){if(photoBusy)return notice('Espera a que cargue la imagen.',true);if(dirty&&!await saveDay())return;loadDay(d)}
function download(content,name){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function validateBackup(raw){if(!raw||raw.version!==1||!raw.entries||typeof raw.entries!=='object'||Array.isArray(raw.entries))throw new Error('Formato de respaldo no reconocido.');const out={version:1,profile:{},entries:{}};for(const k of Object.keys(profileLabels)){const v=raw.profile?.[k]??'';if(typeof v!=='string'||v.length>1000)throw new Error('Portada inválida.');out.profile[k]=v}for(const [d,e]of Object.entries(raw.entries)){if(!dates.includes(d)||!e||typeof e!=='object')throw new Error('Fecha o entrada inválida.');const n={};for(const k of keys){if(typeof e[k]!=='string'||e[k].length>200000)throw new Error('Texto inválido.');n[k]=e[k]}if(!Number.isInteger(e.intensity)||e.intensity<1||e.intensity>5)throw new Error('Intensidad inválida.');if(typeof e.photo!=='string'||e.photo.length>8000000||(e.photo&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(e.photo)))throw new Error('Imagen inválida.');n.photo=e.photo;n.intensity=e.intensity;n.updatedAt=typeof e.updatedAt==='string'?e.updatedAt:'';out.entries[d]=n}return out}
function printMarkup(){const rows=dates.filter(d=>state.entries[d]);let html=`<section class="print-cover"><div class="cover-label">ENTRE DÍAS</div><h1>Mi diario<br>de emociones</h1><p>30 de septiembre al 4 de noviembre de 2026</p><dl>${Object.entries(profileLabels).map(([k,l])=>`<dt>${l}</dt><dd>${esc(state.profile[k]||'________________________')}</dd>`).join('')}</dl><p class="mt-4">${rows.length} días registrados · ${Object.values(state.entries).filter(complete).length} días completos de 36</p></section>`;for(const d of rows){const e=state.entries[d];html+=`<article class="print-entry"><header><div class="print-meta">DÍA ${dates.indexOf(d)+1} · ${esc(label(d))}</div><h2>${esc(e.title||'Mi día')}</h2><div class="print-meta">Lugar: ${esc(e.place||'Sin registrar')} · Emoción: ${esc(e.emotion||'Sin registrar')} · Intensidad: ${e.intensity}/5</div></header>`;for(const [k,l]of [['story','Situación · ¿Qué pasó?'],['thought','Pensamiento · ¿Qué pensé?'],['reflection','Emoción · ¿Cómo me sentí y por qué?'],['behavior','Conducta · ¿Cómo reaccioné?'],['lesson','Una idea útil'],['person','Una persona que fue parte de mi día']])html+=`<h3>${l}</h3><p>${esc(e[k]||'Sin registrar')}</p>`;html+=e.photo?`<figure><img src="${e.photo}" alt="Imagen del ${d}"><figcaption>${esc(e.caption)}</figcaption></figure>`:'<p class="print-missing">Imagen pendiente de agregar.</p>';html+='</article>'}return html}
async function preparePrint(){if(!await saveDay())return;if(!Object.keys(state.entries).length){notice('Primero guarda al menos un día para imprimirlo.',true);return}const pending=36-Object.values(state.entries).filter(complete).length;if(pending&&!confirm(`Hay ${pending} días pendientes o incompletos. Se imprimirá la portada y todos los días registrados, incluidas sus imágenes. ¿Continuar?`))return;$('print-root').innerHTML=printMarkup();try{await Promise.all([...$('print-root').querySelectorAll('img')].map(img=>img.decode()));window.print()}catch{notice('Una imagen no pudo prepararse para imprimir. Vuelve a cargarla antes de continuar.',true)}}
async function init(){for(const[k,l]of Object.entries(profileLabels))$('profile-fields').insertAdjacentHTML('beforeend',`<label for="profile-${k}" class="form-label">${l}</label><input id="profile-${k}" maxlength="300" class="form-control">`);$('editor-fields').disabled=true;try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('entre-dias-diario-2026',1);req.onupgradeneeded=()=>req.result.createObjectStore('diary');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});const data=await new Promise((resolve,reject)=>{const r=db.transaction('diary').objectStore('diary').get('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(data)state=validateBackup(data);for(const k of Object.keys(profileLabels))$('profile-'+k).value=state.profile[k]||'';$('editor-fields').disabled=false;const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;loadDay(dates.includes(today)?today:dates[0])}catch(e){notice('No se pudo abrir el almacenamiento. Abre el sitio en Chrome o Edge con almacenamiento habilitado. '+e.message,true);return}
$('entry-form').addEventListener('submit',async e=>{e.preventDefault();await saveDay()});$('entry-form').addEventListener('input',()=>{dirty=true;$('save-status').textContent='Cambios sin guardar';$('intensity-value').textContent=$('intensity').value+' / 5'});$('calendar').addEventListener('click',e=>{const b=e.target.closest('[data-date]');if(b)switchDay(b.dataset.date)});$('previous').onclick=()=>switchDay(dates[dates.indexOf(selected)-1]);$('next').onclick=()=>switchDay(dates[dates.indexOf(selected)+1]);$('save-profile').onclick=async()=>{if(await saveDay())notice('Portada guardada. Se incluirá al imprimir.')};$('profile-fields').addEventListener('input',()=>{dirty=true});$('remove-photo').onclick=()=>{picture='';$('photo').value='';dirty=true;showPhoto();$('save-status').textContent='Cambios sin guardar'};
$('photo').onchange=async()=>{const file=$('photo').files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024){notice('Usa una imagen JPG, PNG o WebP de hasta 20 MB.',true);$('photo').value='';return}photoBusy=true;$('photo-status').textContent='Preparando imagen…';try{const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);picture=c.toDataURL('image/jpeg',.86)}finally{URL.revokeObjectURL(url)}dirty=true;showPhoto();$('photo-status').textContent='Imagen lista. Presiona Guardar día para conservarla.'}catch{$('photo-status').textContent='No se pudo leer la imagen. Intenta con otro archivo.'}finally{photoBusy=false}};
$('backup').onclick=async()=>{if(photoBusy)return notice('Espera a que cargue la imagen.',true);const backup=structuredClone(state);backup.profile=profileValues();const e=currentEntry();if(keys.some(k=>e[k])||e.photo)backup.entries[selected]={...e,updatedAt:new Date().toISOString()};else delete backup.entries[selected];download(JSON.stringify(backup,null,2),'diario-emociones-respaldo-'+new Date().toISOString().slice(0,10)+'.json');notice('Respaldo descargado con portada, textos e imágenes. Guárdalo en un lugar seguro.')};$('restore').onclick=()=>{if(photoBusy)return notice('Espera a que cargue la imagen.',true);$('import-file').click()};$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>150*1024*1024)throw new Error('El archivo supera 150 MB.');const imported=validateBackup(JSON.parse(await file.text()));if(!confirm('Importar reemplazará los datos de este navegador. Si tienes cambios, cancela y descarga un respaldo primero. ¿Continuar?'))return;await commit(imported);for(const k of Object.keys(profileLabels))$('profile-'+k).value=state.profile[k]||'';loadDay(selected);notice('Respaldo importado, incluidas sus imágenes.')}catch(e){notice('No se importó el archivo: '+e.message,true)}finally{$('import-file').value=''}};$('print').onclick=preparePrint;window.addEventListener('beforeunload',e=>{if(dirty||photoBusy){e.preventDefault();e.returnValue=''}})}
init();
