/* Respaldo GitHub: el token vive solo en memoria y no se exporta. */
(()=>{
'use strict';
let token='',base='',branch='',sha=null,connected=false,busy=false,pending=false;
const panel=document.createElement('details');panel.className='panel mt-3';panel.open=true;
panel.innerHTML=`<summary><strong>Respaldo en GitHub</strong></summary><p class="small mt-3">Conecta antes de escribir. Al guardar se respaldan todos los días y fotos en <code>respaldos/diario.json</code>. En un repositorio público cualquiera podrá leerlos. Puedes elegir un repositorio privado separado, inicializado con un README.</p><div class="row g-2"><div class="col-md-4"><label class="form-label" for="gh-owner">Usuario</label><input class="form-control" id="gh-owner" value="Emilio17Parz"></div><div class="col-md-4"><label class="form-label" for="gh-repo">Repositorio de datos</label><input class="form-control" id="gh-repo" value="diarioemociones"></div><div class="col-md-4"><label class="form-label" for="gh-branch">Rama</label><input class="form-control" id="gh-branch" value="main"></div></div><label class="form-label mt-3" for="gh-token">Token de GitHub · Contents: Read and write</label><input type="password" autocomplete="off" class="form-control" id="gh-token" placeholder="Se usa solo en esta pestaña; no se guarda"><div class="d-flex gap-2 flex-wrap mt-3"><button type="button" class="btn btn-primary" id="gh-connect">Conectar / recuperar de GitHub</button><button type="button" class="btn btn-outline-dark" id="gh-upload">Respaldar ahora</button><button type="button" class="btn btn-outline-secondary" id="gh-disconnect">Desconectar</button></div><p class="small mt-3 mb-0" id="gh-status" role="status" aria-live="polite">Sin conectar. Solo guardado local. Para recuperar ayer, usa Importar con tu respaldo JSON.</p>`;
document.querySelector('.intro').after(panel);
const el=id=>document.getElementById(id);
const message=(s,bad=false)=>{el('gh-status').textContent=s;el('gh-status').style.color=bad?'#a22626':'#146b60'};
async function request(path,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const response=await fetch('https://api.github.com'+path,{...options,signal:controller.signal,cache:'no-store',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(!response.ok){const error=new Error(response.status===401?'Token inválido o vencido.':response.status===403?'Sin permiso de escritura o límite de GitHub.':response.status===404?'Repositorio, rama o archivo no encontrado.':response.status===409||response.status===422?'GitHub cambió o rechazó la escritura. Reconecta para revisar las versiones.':'Error de GitHub: '+response.status);error.status=response.status;throw error}return response}catch(e){if(e.name==='AbortError')throw new Error('La conexión tardó demasiado. Reconecta antes de reintentar.');throw e}finally{clearTimeout(timer)}}
const path=()=>base+'/contents/respaldos/diario.json';
async function remote(readData=true){try{const r=await request(path()+'?ref='+encodeURIComponent(branch));const meta=await r.json();if(meta.type!=='file')throw new Error('La ruta de respaldo no es un archivo.');if(meta.size>50*1024*1024)throw new Error('Respaldo mayor de 50 MB.');if(!readData)return {sha:meta.sha};const raw=await request(base+'/git/blobs/'+meta.sha,{headers:{Accept:'application/vnd.github.raw+json'}});return {sha:meta.sha,data:validateBackup(JSON.parse(await raw.text()))}}catch(e){if(e.status===404)return {sha:null,data:null};throw e}}
function merge(local,cloud){const next=structuredClone(local);if(!cloud)return next;for(const [d,e] of Object.entries(cloud.entries)){if(!next.entries[d])next.entries[d]=e;else if(JSON.stringify(next.entries[d])!==JSON.stringify(e)){const answer=prompt('Hay dos versiones del '+d+'. Escribe LOCAL para conservar este dispositivo o GITHUB para recuperar la nube. Cancelar detiene la conexión.','GITHUB');if(answer===null)throw new Error('Conexión cancelada; no se cambiaron tus datos.');if(answer.toUpperCase()==='GITHUB')next.entries[d]=e;else if(answer.toUpperCase()!=='LOCAL')throw new Error('Opción inválida; no se cambiaron tus datos.')}}for(const [k,v]of Object.entries(cloud.profile))if(!next.profile[k])next.profile[k]=v;return next}
function lock(value){busy=value;for(const id of ['gh-connect','gh-upload','gh-disconnect'])el(id).disabled=value;el('editor-fields').disabled=value;el('restore').disabled=value;el('save-profile').disabled=value;el('print').disabled=value;el('calendar').style.pointerEvents=value?'none':'';for(const k of Object.keys(profileLabels))el('profile-'+k).disabled=value;el('previous').disabled=value||selected===dates[0];el('next').disabled=value||selected===dates.at(-1)}
function encode(text){const bytes=new TextEncoder().encode(text);let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
async function upload(){if(!connected)return message('Guardado local. Conecta GitHub para respaldarlo.',true);if(busy){pending=true;return}lock(true);pending=false;message('Subiendo respaldo a GitHub… No cierres esta pestaña.');try{const snapshot=JSON.stringify(state);if(new TextEncoder().encode(snapshot).length>50*1024*1024)throw new Error('El respaldo supera 50 MB. Descárgalo localmente.');const current=await remote(false);if(current.sha!==sha)throw new Error('El respaldo cambió en otro dispositivo. Reconecta para combinar las versiones antes de subir.');const content=encode(snapshot);const r=await request(path(),{method:'PUT',body:JSON.stringify({message:'Respaldar diario '+new Date().toISOString(),branch,content,...(sha?{sha}:{})})});const result=await r.json();sha=result.content.sha;message('Respaldado en GitHub · '+new Date().toLocaleString('es-MX'));}catch(e){connected=false;pending=false;message('Tus datos siguen guardados localmente. NO se confirmó el respaldo: '+e.message+' Vuelve a conectar.',true)}finally{lock(false);if(pending&&connected)upload()}}
el('gh-connect').onclick=async()=>{if(busy||photoBusy)return message('Espera a que termine la operación actual.',true);if(!db)return message('El diario todavía no está listo.',true);connected=false;if(dirty&&!await saveDay())return;lock(true);try{token=el('gh-token').value.trim()||token;el('gh-token').value='';if(!token)throw new Error('Introduce tu token.');const owner=el('gh-owner').value.trim(),repo=el('gh-repo').value.trim();branch=el('gh-branch').value.trim();if(!/^[A-Za-z0-9-]+$/.test(owner)||!/^[-A-Za-z0-9_.]+$/.test(repo)||!branch)throw new Error('Revisa usuario, repositorio y rama.');base='/repos/'+owner+'/'+repo;const info=await (await request(base)).json();await request(base+'/branches/'+encodeURIComponent(branch));if(!info.private&&!confirm('Este repositorio es PÚBLICO. Los textos, datos de portada y fotos serán públicos al guardar. ¿Quieres usarlo de todos modos?'))throw new Error('Cancelado. Puedes usar un repositorio privado para los datos.');const cloud=await remote();const combined=merge(state,cloud.data);await commit(combined);sha=cloud.sha;for(const k of Object.keys(profileLabels))el('profile-'+k).value=state.profile[k]||'';loadDay(selected);connected=true;message('Conectado. Datos recuperados y combinados. Pulsa Guardar día o Respaldar ahora para subirlos.');}catch(e){connected=false;message(e.message,true)}finally{lock(false)}};
el('gh-upload').onclick=async()=>{if(!connected)return message('Conecta GitHub primero.',true);if(photoBusy)return message('Espera a que cargue la foto.',true);if(dirty){await saveDay()}else await upload()};
el('gh-disconnect').onclick=()=>{connected=false;token='';el('gh-token').value='';message('Desconectado. Los datos locales siguen disponibles.')};
window.addEventListener('diary-saved',()=>{if(connected)upload();else message('Guardado local. Conecta GitHub para subir el respaldo.',true)});
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});
})();
